# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cred',
            old_name='wiegand_hexfield',
            new_name='wiegand_hex',
        ),
    ]
