# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creds', '0002_auto_20171120_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cred', to=settings.AUTH_USER_MODEL),
        ),
    ]
